# Generated by Django 4.1.7 on 2023-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0002_grp_usrs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usrs",
            old_name="idgrp",
            new_name="grp_id",
        ),
        migrations.RenameField(
            model_name="usrs",
            old_name="idusr",
            new_name="usr_id",
        ),
    ]
