# Generated by Django 4.1.7 on 2023-03-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0003_rename_idgrp_usrs_grp_id_rename_idusr_usrs_usr_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grp",
            old_name="idgrp",
            new_name="grp_id",
        ),
    ]
