# Generated by Django 4.1.7 on 2023-03-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0004_rename_idgrp_grp_grp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grp",
            name="grp_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usrs",
            name="usr_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
