# Generated by Django 4.1.7 on 2023-03-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0005_alter_grp_grp_id_alter_usrs_usr_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grp",
            name="islast",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
