# Generated by Django 4.1.7 on 2023-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0006_alter_grp_islast"),
    ]

    operations = [
        migrations.AddField(
            model_name="usrs",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
