# Generated by Django 4.1.7 on 2023-03-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0007_usrs_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usrs",
            name="token",
        ),
    ]
